# Generated by Django 4.2.6 on 2023-10-05 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('texto', models.CharField(max_length=2000)),
                ('dataPublicacao', models.DateField()),
            ],
        ),
    ]
